language: cpp

compiler:
    - clang

script:
    - make tests


notifications:
    email:
        recipients:
            - mm8348@nyu.edu
            - sl6219@nyu.edu
        on_success: always
        on_failure: never

